# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua
#0 animacji 0 bloatu 0 paskow 
#zawsze pelen ekran 0 gapsow i smieci 
#prawie z niewiadomych przyczyn nie dziala terminal#ctrl alt f1/f12 tty 
#mainMod + mouse + click hold floating window 
#lshift + rhift zmienia klawiature pl/gb 

env = XDG_DATA_DIRS,/data/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
env = FLATPAK_USER_DIR,/data/flatpak
env = MOZ_ENABLE_WAYLAND,1

autostart {
    exec = wl-paste --type text --watch cliphist store
    exec = wl-paste --type image --watch cliphist store
    exec = dunst
    exec = kbnotify
    exec = /usr/lib/xfce-polkit/xfce-polkit
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 0
    allow_tearing = true
}

misc {
    disable_autoreload = true
    background_color = 0x111111
    disable_hyprland_logo = true 
    enable_swallow = false 
}


input {
    kb_layout = pl,gb
    kb_options = grp:shifts_toggle
}

animations {
    enabled = false

}


monitor=DVI-D-1,preferred,0x0,1
monitor=DP-1,preferred,1920x0,1

workspace=1,monitor:DVI-D-1,default:true
workspace=2,monitor:DVI-D-1
workspace=3,monitor:DVI-D-1
workspace=4,monitor:DVI-D-1
workspace=5,monitor:DVI-D-1
workspace=6,monitor:DP-1,default:true
workspace=7,monitor:DP-1
workspace=8,monitor:DP-1
workspace=9,monitor:DP-1
workspace=10,monitor:DP-1
$fileManager = thunar
$super = SUPER
$terminal = foot
$menu = $HOME/.config/src/menu

bind = $super, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
#high low sound 
bind = $super, H, exec, wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+ && notify-send -t 800 -u low -h string:x-dunst-stack-tag:vol "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%d%%", $2*100}')"
bind = $super, L, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send -t 800 -u low -h string:x-dunst-stack-tag:vol "Volume" "$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{printf "%d%%", $2*100}')"

bind = $super, W, exec, $menu
bind = $super, G, exec, rofi -show drun -show-icons -drun-categories Game
bind = $super, Q, forcekillactive  
bind = $super, Return, exec, $terminal 

#okna
bind = $super, left, movefocus, l
bind = $super, right, movefocus, r
bind = $super, up, movefocus, u
bind = $super, down, movefocus, d
bind = $super SHIFT, left, movewindow, l
bind = $super SHIFT, right, movewindow, r

#monitor
bind = $super, comma, focusmonitor, l
bind = $super, period, focusmonitor, r
bind = $super SHIFT, comma, movewindow, mon:l
bind = $super SHIFT, period, movewindow, mon:r

#workspace (oba monitory jednoczesnie)
$wsswitch = $HOME/.config/src/workspcswitch
bind = $super, Z, exec, $wsswitch prev
bind = $super, X, exec, $wsswitch next
bind = $super SHIFT, Z, exec, $wsswitch move_prev
bind = $super SHIFT, X, exec, $wsswitch move_next

#tty
bind = CTRL ALT, F1, exec, chvt 1
bind = CTRL ALT, F3, exec, chvt 3
bind = CTRL ALT, F4, exec, chvt 4
bind = CTRL ALT, F5, exec, chvt 5